<?php
$listarray = array ( array ( 'label' => 'Pfad',
                             'name' => 'pfad', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldpfad' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Bemerkung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbemerk' ),
                     array ( 'label' => 'Typ',
                             'name' => 'dbtyp',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblselect',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_select' ),
                     array ( 'label' => 'List',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'tablelist.php?menu=table',
                             'dbfield' => 'icon-book' ));

$pararray = array ( 'headline' => 'Datenbanken',
                    'dbtable' => 'tbldatabase',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>